---
name: 'MLibrary Deploy to Kubernetes Cluster'
description: 'Deploys a ghcr image to a Kubernetes Cluster'
inputs:
  github_username:
    required: true
    default: ${{ github.actor }}
  github_token:
    required: true
  image:
    required: true
    description: organization/image_name
  cluster_ca:
    required: true
  cluster_server:
    require: true
  namespace_token:
    required: true
  namespace:
    required: true
  deployment:
    required: true
    default: 'web'
  container:
    required: true
    default: 'web'
  type:
    required: true
    default: 'deployment'
    description: "'deployment' or 'cronjob'"
  cronjob_name:
    required: false

runs:
  using: "composite"
  steps:
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.github_username }}
        password: ${{ inputs.github_token }}
    - name: Prepend ghcr.io to image name if necessary
      id: image_name
      uses: actions/github-script@v6
      env:
        IMAGE: ${{ inputs.image }}
      with:
        script: |
          image = process.env.IMAGE
          if(!image.startsWith('ghcr.io/')) {
            image = "ghcr.io/" + image
          }
          core.setOutput('image',image)
    - name: Check that the image & tag exist
      run: docker manifest inspect "$IMAGE" > /dev/null
      shell: bash
      env:
        IMAGE: ${{ steps.image_name.outputs.image }}
    - uses: azure/setup-kubectl@v1
    - name: Authenticate with kubernetes
      shell: bash
      run: |
        mkdir -p ${HOME}/.kube/certs/cluster
        echo ${{ inputs.cluster_ca }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
        kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server="$CLUSTER_SERVER"
        kubectl config set-credentials default --token=$(echo "$NAMESPACE_TOKEN" | base64 -d)
        kubectl config set-context default --cluster=cluster --user=default --namespace="$NAMESPACE"
        kubectl config use-context default
      env:
        CLUSTER_CA: ${{ inputs.cluster_ca }}
        CLUSTER_SERVER: ${{ inputs.cluster_server }}
        NAMESPACE_TOKEN: ${{ inputs.namespace_token }}
        NAMESPACE: ${{ inputs.namespace }}
    - name: Deploy
      shell: bash
      run: |
        case "$TYPE" in
          deployment)
            kubectl set image deployment "$DEPLOYMENT" "$CONTAINER"="$IMAGE"
            ;;
          cronjob)
            json=$(cat <<EOT
            [
              {
                "op": "replace",
                "path": "/spec/jobTemplate/spec/template/spec/containers/0/image",
                "value": "$IMAGE"
              }
            ]
        EOT
            )
            kubectl patch cronjob "$CRONJOB_NAME" --type=json -p="$json"
            ;;
          *)
            echo "type must be deployment or cronjob"
            exit 1;
        esac
      env:
        TYPE: ${{ inputs.type }}
        DEPLOYMENT: ${{ inputs.deployment }}
        CRONJOB_NAME: ${{ inputs.cronjob_name }}
        CONTAINER: ${{ inputs.container }}
        IMAGE: ${{ steps.image_name.outputs.image }}
